### ISSUE TITLE
Don't start profiler on load when it was stopped in the previous session

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/Gecko-Profiler-Addon#10]
Keep a preference around to store the state of the profiler and don't start it automatically when it was stopped in the last browser session.

**Comment by gregtatum** [comment]
I also think it should be off by default. Most users probably don't want it always running, as there is an overhead to do so. There is also a similar bug filed by @juj on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1349496)

**Comment by clarkbw** [comment]
See also #45

**Comment by gregtatum** [comment]
Closed as no longer valid with the new built-in workflow.
