### ISSUE TITLE
Gecko profiler doesn't show its correct icon on toolbar

### ISSUE THREAD

**Issue by upsuper** [firefox-devtools/Gecko-Profiler-Addon#103]
After upgrading to 0.18, it seems the icon doesn't show correctly. See the screenshot below.

![image](https://user-images.githubusercontent.com/333750/34852994-8520f8aa-f785-11e7-8723-e04e3b6da7a2.png)

**Comment by julienw** [comment]
@upsuper Which Firefox version is this ? Also, which OS are you using ?

We changed how the icons are defined in https://github.com/devtools-html/Gecko-Profiler-Addon/commit/a2288b02672d25ddea0f3aa2b5a960fe095996f6 but the upgrade worked for me flawlessly on Nightly...

**Comment by upsuper** [comment]
Yeah it seems to work fine on nightly, but shows this on both release (on my macOS) and beta (on my Windows).

**Comment by julienw** [comment]
I actually see the same as you on my stable. I'm a bit sad especially that I left `default_icon` on purpose, in case the user uses a Firefox that doesn't understand `theme_icons`. But stable should understnad `theme_icons`, but looks like there was a bug in Firefox... mozregression gave me https://bugzilla.mozilla.org/show_bug.cgi?id=1419940

**Comment by julienw** [comment]
I think this is not fixable on 57 and 58 except going back to the previous state, where we don't have a good icon for dark theme. I'm tempted to do nothing as the gecko profiler is most often used on nightly, by developers that don't mind so much about this, and 59 will be released in 8 weeks.

**Comment by past** [comment]
Is this issue still valid? Even ESR is at 60 by now.
