### ISSUE TITLE
Use the new `contentScripts` API to register our content script

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#107]
Currently we rely on a complicated set-up to inject our `content.js`. The new API `contentScripts` (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts/register) should make this a lot easier.

We may need to modify the script hash in perf.html's CSP header.

**Comment by gregtatum** [comment]
This is no longer needed with the new system.
