### ISSUE TITLE
Add the responsiveness feature, and make it on by default

### ISSUE THREAD

**Issue by gregtatum** [firefox-devtools/Gecko-Profiler-Addon#108]
This is required before [Bug 1447338](https://bugzilla.mozilla.org/show_bug.cgi?id=1447338) can land.

**Comment by gregtatum** [comment]
If I add an unknown "feature", an error is thrown. I'll have to investigate this further:

```
Error: Type error for parameter settings (Error processing features.2: Invalid enumeration value "responsiveness") for geckoProfiler.start.
```

**Comment by mstange** [comment]
Specified features are checked against the list in the webextension schema. I don't know if there is a way to list the supported features programmatically.

**Comment by gregtatum** [comment]
@squarewave I think I'd like to list out the features through a webextension API through something like `browser.geckoProfiler.getFeatures()`, or even just call out something like `browser.geckoProfiler.supportsFeature("responsiveness")`. The problem I'm having is figuring out how to ask that question programmatically without duplicating the existing lists of features. I _could_ just duplicate the list, but that seems error prone. Do you have a recommendation on how to pull it in? I'll file a follow-up bug on bugzilla.

* Features defined in the extension schema: https://searchfox.org/mozilla-central/rev/d0413b711da4dac72b237d0895daba2537f1514c/browser/components/extensions/schemas/geckoProfiler.json#25-37
* Features defined in the gecko profiler: https://searchfox.org/mozilla-central/rev/d0413b711da4dac72b237d0895daba2537f1514c/tools/profiler/public/GeckoProfiler.h#101-134

**Comment by squarewave** [comment]
Unfortunately I don't know of a way, but I'm not necessarily a WebExtensions API expert. There doesn't seem to be any example I can find of this kind of thing among existing WebExtensions APIs, so I wouldn't be surprised if you had to do a bit of a dance to get it. You could ask in the webextensions IRC, or r?kmag on the patch. Sorry, wish I could be more help!

**Comment by gregtatum** [comment]
Hey @kmaglione, do you have thoughts on my above question?

**Comment by gregtatum** [comment]
Nevermind, Markus provided me with an nsIProfiler method that can accomplish this.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1454481

**Comment by gregtatum** [comment]
And in the next step of this thrilling journey, apparently there is a `browser.geckoProfiler.ProfilerFeature` which contains the known features. There we go.
