### ISSUE TITLE
Show privacy prompt when saving profile json locally?

### ISSUE THREAD

**Issue by overholt** [firefox-devtools/Gecko-Profiler-Addon#115]
Someone attached a .json file to bugzilla but I'm not sure they knew their URLs would be included so I'm reticent to share it myself via perf-html.io. Should we show the prompt for local saving, too?

**Comment by mstange** [comment]
I'm not sure if we need to prompt, but we should at least show a warning. "This is the stuff that's contained in the profile, be careful when sharing it."

**Comment by mstange** [comment]
ah, wrong repo. Can you refile the issue in https://github.com/devtools-html/perf.html/issues/ ?
