### ISSUE TITLE
Completely wrong symbolication information on Linux

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#12]
As seen e.g. here: https://i.imgur.com/01aFTed.png

**Comment by mstange** [comment]
This was on a Nightly, so we tried to pull symbols from symbols.mozilla.org first. That failed with a NetworkError (we don't know why), so we fell back to local symbolication. But apparently Nightlies on linux just don't have that much symbol information in them (or maybe dump_syms doesn't check the right parts?), so the symbols that are displayed are the only ones we have.

**Comment by gregtatum** [comment]
Closing as no longer valid.
