### ISSUE TITLE
Put "Renderer" in the thread list automatically if unset by user and WebRender is enabled

### ISSUE THREAD

**Issue by mikeconley** [firefox-devtools/Gecko-Profiler-Addon#126]
Threads named "Renderer" are very handy when profiling issues with WebRender. We should try to make it easier to capture useful WebRender profiles the first time - I think this might help.

**Comment by julienw** [comment]
I don't like the idea of enabling something when it's unset. However maybe `Renderer` could be in the default setting ? I believe that in non-webrender builds this would be ignored. Thoughts @mstange @gregtatum ?

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625543
