### ISSUE TITLE
Addon crashes Nightly

### ISSUE THREAD

**Issue by zoepage** [firefox-devtools/Gecko-Profiler-Addon#128]
When the `screenshot capture` feature is enabled, it crashes Nightly.

STR:
![screen shot 2018-10-01 at 14 42 39](https://user-images.githubusercontent.com/562354/46289493-878a9d80-c589-11e8-8c41-9ccc5271f16b.png)

1. Apply settings as in screenshot above
2. click `Apply (restart profiler)`
3. click somewhere except the add on box

ER:
Applies new settings

AR:
Crashes Nightly

Crash reports from 2 different environments:
https://crash-stats.mozilla.com/report/index/fe93fbe0-1e22-4927-9cc1-c5b140181001
https://crash-stats.mozilla.com/report/index/57d663c2-e19a-4874-9e02-ff2930181001

**Comment by past** [comment]
This is not an add-on bug, this is a Firefox bug. Can you open a bug in Core::Gecko Profiler instead? It should block the main screenshots implementation bug.

**Comment by julienw** [comment]
Somebody filed in https://bugzilla.mozilla.org/show_bug.cgi?id=1495463 already :)
