### ISSUE TITLE
Profiler addon slider tracks missing for Interval & Buffer Size

### ISSUE THREAD

**Issue by dholbert** [firefox-devtools/Gecko-Profiler-Addon#131]
The profiler addon's slider "tracks" (for the Interval & Buffer Size options) are missing for me, on Ubuntu 18.10 Linux, with Firefox Nightly.

I think this is a ~recent regression in the addon UI, though I'm not entirely sure. (Could conceivably be from me updating my Ubuntu from 18.04 to 18.10 and getting some native theme changes, too.)  In any case, it's something we should address.

Screenshot:
![screenshot-profiler-missingtracks](https://user-images.githubusercontent.com/426803/47461971-f4fba980-d796-11e8-8d90-3ecd65734ede.png)

CC @canaltinova

**Comment by dholbert** [comment]
Hmm, this might just be an Ubuntu theming regression, actually (possibly by design but with kind of annoying effects)...

This trivial data URL gives me the exact same "ghostly floating orb with no track" rendering:
````
data:text/html,<input type="range">
````

**Comment by dholbert** [comment]
Yeah, if I change my Ubuntu theme from its default "Yaru" to "Adwaita", then this widget changes rendering such that it's got a visible track.

So this is just a silly Ubuntu theme change with bad default behavior. :-/  Probably not worth tracking / worrying about too much here -- I'll close and see if I can find an appropriate place to file upstream.

**Comment by dholbert** [comment]
I filed https://github.com/ubuntu/yaru/issues/930 on this issue in the Ubuntu 18.10 default theme ("Yaru"), BTW.

**Comment by julienw** [comment]
I remember a similar issue happening somewhere else in Firefox (don't remember where though :/)

We recently changed this popup view so that should be the reason. If you find a workaround we'd be happy to apply it, so please tell us if you have anything!

**Comment by dholbert** [comment]
Yeah, I initially blamed the redesign, but I think my Ubuntu upgrade + native theme change is the real culprit.

Easy workaround is to style these input type="range" elements with "-moz-appearance: none" to remove the native look & feel. Our unthemed slider widgets look pretty reasonable (though they don't feel as "native" of course)

**Comment by julienw** [comment]
Do you think there could be an underlying issue in Firefox actually, that we don't get some value from the native theme?

I found the issue I once had: https://bugzilla.mozilla.org/show_bug.cgi?id=1187237
This looks a lot like what you're describing.

I don't have the issue myself at the moment, but I believe there's something we can do in Firefox.

**Comment by dholbert** [comment]
Yes, it's basically a bug with Firefox not drawing the full gtk widget. I've filled https://bugzilla.mozilla.org/show_bug.cgi?id=1501858 on it.
