### ISSUE TITLE
Show keyboard hint to start/stop profiler

### ISSUE THREAD

**Issue by squelart** [firefox-devtools/Gecko-Profiler-Addon#132]
When opening the extension popup, the first two boxes show:
- The profiler is stopped   [start]
- Capture profile   ctrl+shift+2

For helpfulness and consistency, it would be great if we could show "ctrl+shift+1" in the first box.

For extra consistency, maybe the [start] button should be moved to a bigger box like the 2nd one? (And the current state would stay at the very top.) But this is less important, and I'm not a UI expert, and I have no taste. ;-)

**Comment by julienw** [comment]
yeah I think this would be very useful indeed :)

**Comment by gregtatum** [comment]
The shortcuts are very obvious in the new UI. Closing as resolved.
