### ISSUE TITLE
If profiler is stopped, applying settings changes will start it

### ISSUE THREAD

**Issue by leplatrem** [firefox-devtools/Gecko-Profiler-Addon#136]
- profiler is stopped
- change settings, and apply/restart
- profiler is started

Would it possible to leave it stopped after applying changes? Or change the UI if no «apply» is required if the profiler is stopped.

**Comment by gregtatum** [comment]
I think the new workflow is a bit different, and I'm not sure if this is still relevant. Closing as invalid. Feel free to re-file in Bugzilla under DevTools :: Performance Tools (Profiler/Timeline) if this is still an issue.
