### ISSUE TITLE
yarn.lock is included in the xpi

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#144]
For some reason, this command doesn't exclude yarn.lock from the xpi:
https://github.com/devtools-html/Gecko-Profiler-Addon/blob/da6e335f9918305c2a32462cba4ab34b6e41f08b/package.json#L28

` "sign-extension:step1": "web-ext sign -i README.md package.json *.rdf transition resources --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET",`

cc @julienw

**Comment by julienw** [comment]
Well, we probably just need to add `yarn.lock` to this list of files to ignore :)
