### ISSUE TITLE
If the Screenshots checkbox is checked, force-profile the Compositor thread

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#148]
Screenshots are stored as markers in the compositor thread. If you don't profile the compositor thread, the markers don't end up in the profile, and you won't get any screenshots. We should avoid this failure case somehow. We could change the platform side to store screenshots in an extra screenshot list on the process, instead of as markers on a thread... or we could change the add-on to make sure we always profile the compositor thread if screenshots are selected.

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625537
