### ISSUE TITLE
When window length is "undefined" it shouldn't show "sec" as well

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#149]
Currently when "window length" is undefined we have "sec" as unit as well. We don't see it very well because it's out of the window, but this causes an horizontal scrollbar too.

**Comment by canova** [comment]
Huh, interesting. Ideally, it shouldn't be undefined in the beginning.

**Comment by julienw** [comment]
Actually I think it's "undefined" after an upgrade (from when the setting wasn't existing) and if the user doesn't change the setting. So if it's "undefined" we should change it to the default value.

**Comment by canova** [comment]
That makes sense. I'll look into it, thanks!
