### ISSUE TITLE
Symbol table parsing uses too much memory, causes crashes in 32 bit builds

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#15]
After fetching the symbol table dump from symbols.mozilla.org as a blob, `parse-sym-worker.js` converts the whole blob to a string before processing that string. Apparently in 32 bit builds we can run out of memory during this step, see [this conversation in #developers](http://logs.glob.uno/?c=mozilla%23developers&s=29+Dec+2016&e=29+Dec+2016#c1527394) and [this crash report in FileReaderSync.prototype.readAsText](https://crash-stats.mozilla.com/report/index/6c92af0e-94ec-4338-9e1b-0f3262161229).

It would be nice to find a way to do the processing in chunks. E.g. we could rewrite the function to operate on Uint8Array chunks that we get by `slice()`ing the blob.

We could also try make sure that we're not running too many symbol parsing worker threads at the same time.

**Comment by gregtatum** [comment]
I'm closing as no longer valid, since I'm not sure it accurately describes the current state of things.
