### ISSUE TITLE
The default sampling interval should be 2ms on Windows

### ISSUE THREAD

**Issue by fqueze** [firefox-devtools/Gecko-Profiler-Addon#158]
It seems we are never able to sample more than every 2ms on Windows, so I think we should increase the default sampling interval (currently 1ms) to 2ms.

Opening an issue here for tracking, but this may need a patch in mozilla-central and a change in the Gecko Profiler add-on.

**Comment by gregtatum** [comment]
> julienw  transferred this issue from firefox-devtools/profiler

😲

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625535
