### ISSUE TITLE
"Start" button is partially overlapped by vertical scrollbar 

### ISSUE THREAD

**Issue by rajmeghpara** [firefox-devtools/Gecko-Profiler-Addon#159]
Kindly look at the "Start" button in the below image:

<img width="401" alt="screenshot 2019-03-05 at 1 47 05 am" src="https://user-images.githubusercontent.com/16744065/53785192-ad9fd980-3f3d-11e9-890e-33e226d01dfc.png">

**Comment by julienw** [comment]
Thanks! Maybe we can add some margin to the start button.
Note this doesn't happen on Linux because the scrollbar is fixed. I wonder how this behaves on Windows.

**Comment by gregtatum** [comment]
It's fine on my Windows machine.

**Comment by Jo-IE** [comment]
I would like to work on this if it is up for grabs, someone please let me know. Thanks!

**Comment by Jo-IE** [comment]
I get an error when I run npm start. Could someone let me know what I'm doing wrong? Thanks! This is my error below:

Error: spawn /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckoprofiler@ start: `web-ext run --firefox=$npm_package_config_firefox`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geckoprofiler@ start script.

**Comment by julienw** [comment]
Hey @Jo-IE, thanks for trying at least !

We're sunsetting this addon these days, so if you're looking for something to work on, I'd suggest that you look at our list of goot first issues in the profiler UI by looking at our [CONTRIBUTING document](https://github.com/firefox-devtools/profiler/blob/master/CONTRIBUTING.md).

**Comment by Jo-IE** [comment]
Thanks @julienw !

**Comment by gregtatum** [comment]
Resolved as no longer needed.
