### ISSUE TITLE
Pull all/most settings from Firefox (e.g., thread list, features...)

### ISSUE THREAD

**Issue by squelart** [firefox-devtools/Gecko-Profiler-Addon#163]
Currently most things displayed by the add-on are hard-coded: Profiling settings, list of threads, features, and defaults thereof.
I think ideally all this information could&should be provided by Firefox.
This would make it easier to maintain the add-on, and to stay in sync with the Firefox version in which the add-on operates.

One particular scenario I'm thinking of, would be a Gecko dev registering a new thread, and wondering why it's not showing up in the list.

(I'm happy to help on the Gecko side if someone wants to take this bug here.)

**Comment by squelart** [comment]
This could help close a lot of issues here, e.g.: #42 #79 #95 #158 
And maybe, with a bit more work: #83 #148

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625532
