### ISSUE TITLE
Offer hint&link to Gecko devs re:threads

### ISSUE THREAD

**Issue by squelart** [firefox-devtools/Gecko-Profiler-Addon#164]
Gecko devs may not know about registering threads in Gecko and adding the new thread name in the entry box.
We could offer a hint, e.g.: "Firefox developers may register more threads", with a link to the appropriate docs (not yet written, could link to Profiler.h in Searchfox in the meantime).

**Comment by gregtatum** [comment]
The new UI has better thread selections, plus presets. Marking as resolved.
