### ISSUE TITLE
(Optionally?) gzip profile data before sending to perf-html

### ISSUE THREAD

**Issue by jimporter** [firefox-devtools/Gecko-Profiler-Addon#165]
This is the add-on version of [bug 1551992](https://bugzilla.mozilla.org/show_bug.cgi?id=1551992) and firefox-devtools/profiler#2044.

Profiles can get pretty big, especially with tracelogger data (which increases the profile's size by 8-10x); even short profiles with tracelogger on can be over 100 MB! To mitigate this, we'd like to add support for gzipping the profile data before sending it to perf-html. This is mainly useful for cutting tracelogger profiles down to reasonable sizes again, but ultimately helps with all profiles. See [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1551992#c3) for some comparisons.

My plan is to add a new method called `getProfileAsGzippedArrayBuffer` and use it in this add-on, and then decompress the data in perf-html. It would probably be simplest to do this 100% of the time, but if folks think it'd be better, we could add a pref for gzipping vs sending uncompressed data.

(Compressing profile data within Firefox itself also works around the fact that our IPC code that sends the data to the add-on has a [max of 256 MB](https://bugzilla.mozilla.org/show_bug.cgi?id=1544544#c3).)

**Comment by gregtatum** [comment]
This is no longer needed, as the add-on is deprecated. The built-in popup does this.
