### ISSUE TITLE
`*` does not work in the list of threads, but `*,` works

### ISSUE THREAD

**Issue by padenot** [firefox-devtools/Gecko-Profiler-Addon#169]
When trying to profile all threads, I put in `*`. This seemed to do something at first, because Activity Monitor reported increased CPU usage, but then I captured the profile and it said:

> Error: No threads were captured in this profile, there is nothing to display.

`*,` works perfectly however.

**Comment by gregtatum** [comment]
I'm closing this in favor of [Bug 1569630](https://bugzilla.mozilla.org/show_bug.cgi?id=1569630). We're in an awkward transition between the add-on and the built-in profiler popup.
