### ISSUE TITLE
Add support for thread groups, for helping to profile performance problems in the field

### ISSUE THREAD

**Issue by padenot** [firefox-devtools/Gecko-Profiler-Addon#170]
Short of having the ability to record all threads all the time, it would be interesting to be able to have a single tickbox/dropdown that would start recording a certain group of threads and apply some settings for a particular use case.

In my situation ([BMO#1568286](https://bugzilla.mozilla.org/show_bug.cgi?id=1568286)), I need to have a user record a profile of something on their computer, that I can't repro myself. I had to find the names of the threads to profile, by entering `*,` in the thread list (`*` does not seem to work for some reason, filed as #169). Then I captured the profile and listed manually the threads to record, in my case:

>GeckoMain,Compositor,MediaPDecoder,MediaTimer,MediaPlayback,MediaDecoderStateMachine

Then, after capturing the profile I had to manually click to display the right lanes (which is not a big deal since I'm going to do it, not the user I'm getting the profile from), but could be smoother, I've already told the profiler which threads I was interested in (filed as  #168).

Taking as example what I know best, media, it would go like this:
- The user chooses a particular "mode", say, Media 
- This lower the interval to 1ms (or the lowest the platform can do, I just say #158), increases window length and buffer size
- It disables screenshoting (this has too much interplay with our type of workload and is not necessary) and other options that we don't need
- It adds a specific set of threads to profile, but other threads can be manually added

Some integration with #163 would be amazing, since Gecko developers would be responsible to maintain the list of threads and settings for a particular use case.

**Comment by gregtatum** [comment]
We're looking into a very similar feature right now with preset profiling modes. I'm leaving this open for now, but most likely we'll have a dedicated bug somewhere for implementing it. We're currently looking for UX help in this area. Thanks for validating this idea :)

**Comment by padenot** [comment]
My experience is that even developers are unable to follow the simple instructions to record specific threads the first time around, so it takes at least two round trips to get the right info to diagnose a problem in the field, and that's when I can get an answer at all after the first one.

It seems quite important to simplify the flow here, at least for my use-case.

**Comment by gregtatum** [comment]
I wonder if we could send people to a URL on `profiler.firefox.com`, e.g. `profiler.firefox.com/recording-mode/media` that would select the correct recording mode for the profiler, then they could follow their steps to reproduce.

**Comment by padenot** [comment]
This would be amazing and solve all the problems above.

**Comment by julienw** [comment]
How would we configure this then? In JSON (or other format) files stored in mozilla-central, like in `/tools/profiler/recording-mode/media.yaml` ?

**Comment by julienw** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1589681 to track this work to be done on the popup in Firefox.

**Comment by gregtatum** [comment]
Resolved by https://bugzilla.mozilla.org/show_bug.cgi?id=1597381
