### ISSUE TITLE
Point out this is getting superseeded

### ISSUE THREAD

**Issue by mirh** [firefox-devtools/Gecko-Profiler-Addon#173]
[BMO#about-profiling](https://bugzilla.mozilla.org/show_bug.cgi?id=1597371)
[BMO#1612516](https://bugzilla.mozilla.org/show_bug.cgi?id=1612516)

**Comment by julienw** [comment]
Thanks for this issue!
Indeed we're working on migrating away from add-on. But as of now this is still our prefered tool for the general public. We'll have a migration path for our current add-on users.

**Comment by julienw** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1572786 about the migration path.
