### ISSUE TITLE
clicking on non-GeckoMain process doesn't zoom in on expensive call stacks.

### ISSUE THREAD

**Issue by froydnj** [firefox-devtools/Gecko-Profiler-Addon#19]
When I open up a profile, I see the "GeckoMain [default]" profile, with a callstack that's taking up the majority of the time already opened up.  Usually, this is somewhere down inside `__poll` on Linux, which is not too interesting.  So I click on the "GeckoMain [tab]" profile, which presents me with a single line labeled `(root)`.  I then have to click and lick and lick to get down to the interesting point; it would be nice if the profiler automatically unfolded the interesting stacks like it did for the main process.

This applies to the Compositor timeline, and probably other threads if they are being profiled.

**Comment by gregtatum** [comment]
I believe this is implemented in perf.html.
