### ISSUE TITLE
Convert to WebExtension

### ISSUE THREAD

**Issue by clarkbw** [firefox-devtools/Gecko-Profiler-Addon#20]
[bug 1326572](https://bugzilla.mozilla.org/show_bug.cgi?id=1326572) is tracking the work required to implement a new WebExtension API that would allow this add-on become a WebExtension by simply consuming the API Firefox provides.

Once we have a working API this extension will need to be converted to a WebExtension.  In the short term it is possible for a hybrid conversion where we convert the UI into a WebExtension and continue to provide our own API using the bootstrap extension.

**Comment by mstange** [comment]
@squarewave is working on this in https://github.com/squarewave/gecko-profiler-webextension .

**Comment by clarkbw** [comment]
Done in #44
