### ISSUE TITLE
Profiling restarts

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#31]
With the current profiler addon it doesn't seem possible to capture profiling data of shutdown/startup operations.

It was possible with the previous version, that had a "restart" button.

**Comment by mstange** [comment]
Yes, this would be a good addition to the add-on.

The old add-on's code to handle this is inside [main.js](https://github.com/bgirard/Gecko-Profiler-Addon/blob/master/src/lib/main.js), search for `profileRestart`. Basically, if the environment variable `MOZ_PROFILER_STARTUP` is set to a non-empty string, the profiler automatically starts itself on initialization, and if the env var `MOZ_PROFILER_SHUTDOWN` is set to a filename, then the profiler dumps out a profile to that file during shutdown. Restarting Firefox using `appStartup.quit(appStartup.eForceQuit | appStartup.eRestart);` preserves environment variables.

**Comment by mstange** [comment]
I've created [bug 1348023](https://bugzilla.mozilla.org/show_bug.cgi?id=1348023) to track a few platform improvements that we could make for startup profiling.

**Comment by mstange** [comment]
The first step here would be to add the relevant WebExtension APIs. Here's the set of APIs I proposed in [bug 1326572 comment 15](https://bugzilla.mozilla.org/show_bug.cgi?id=1326572#c15):

```
  void triggerRestartAndGatherProfiles({
    shutdown: { /* shutdown profiler settigs */ },
    startup: { /* startup profiler settings */ }
  });
  Promise<GeckoProfile>? getShutdownProfileIfAvailable();
  Promise<GeckoProfile>? getStartupProfileIfAvailable();
```

**Comment by mstange** [comment]
For the shutdown profile, instead of specifying new profiler settings and restarting the profiler, we could also just leave the profiler running with the current settings. Then everything that has been captured in the buffer before the call to `triggerRestartAndGatherProfiles` would also be part of the shutdown profile (if it fits in the buffer).

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625546
