### ISSUE TITLE
Make the addon install on Fennec / Android

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#33]
Currently the add-on can't be installed on Fennec. It's downloading and then nothing.

**Comment by julienw** [comment]
At the very least, we need to add "fennec" to package.json's `engines` dictionary.
=> https://github.com/devtools-html/Gecko-Profiler-Addon/blob/master/package.json#L14

but would that be enough ?

**Comment by gregtatum** [comment]
This is no longer needed with remote profiling support in Gecko.
