### ISSUE TITLE
Support remote profiling

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#35]
As immediate difference with the old support, .so are now (since 52) compressed with xz instead of szip, which is a lot easier.

**Comment by mstange** [comment]
I've done the first steps in #36. Symbolication is still missing.

I think we should address symbolication in three tiers:
 1. Symbolicate Gecko libraries, official builds only. This should only require [bug 1350500](https://bugzilla.mozilla.org/show_bug.cgi?id=1350500) and then we should automatically find the right symbol dump on symbols.mozilla.org.
 2. Symbolicate Gecko libraries from local builds. For this we need to know where the objdir on the developer's machine is, and run dump_syms or nm on the binaries in the objdir. (For nm we need to know where the NDK tools are.)
 3. Symbolicate system libraries from the phone. For this we need to know the absolute paths of those libs ([bug 1350501](https://bugzilla.mozilla.org/show_bug.cgi?id=1350501)), and we need to be able to pull them to the Desktop machine usind adb (so we need to know where adb is).

**Comment by gregtatum** [comment]
Closing in favor of #804

**Comment by gregtatum** [comment]
Woops, re-opening as this is the Gecko Profiler.

**Comment by past** [comment]
For adb we could just depend on the ADB Helper add-on just like WebIDE does.

**Comment by gregtatum** [comment]
This is supported now. I'm not sure the Bug #, as it's been awhile.
