### ISSUE TITLE
Support getting the symbols on a different machine than the machine that capture the profile

### ISSUE THREAD

**Issue by fqueze** [firefox-devtools/Gecko-Profiler-Addon#41]
I tried to profile the Browser UI on a very old machine which only has 1GB of ram. Getting the libxul.so symbols has taken about 15 minutes, without any progress indicator, just the hard disk being noisy. I think the machine was out of memory, and swapping a lot.

It would be nice if getting the symbols could be done on the machine where I'll be studying the profile, rather than on the machine where I'm capturing it.

**Comment by gregtatum** [comment]
We support symbolicating after the fact now. There are so many ways to symbolicate, that it would be good to re-file this with more specific cases if this is still needed. Closing this one for now.
