### ISSUE TITLE
MOZ_PROFILER_STARTUP isn't enough startup

### ISSUE THREAD

**Issue by mirh** [firefox-devtools/Gecko-Profiler-Addon#43]
Or in other words, trying to figure out [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1358283) problem: 
1. log is pretty much empty even if I try to save it as soon as possible after session restore, and even with aforementioned `set` env
2. I seldom was getting `Script: chrome://browser/content/tabbrowser.xml:7246` warnings, and it was pretty obvious there (when UI has time to finally breath and render) that of all the buttons, Profiler one wasn't there. And at this point I was already 3/4 past the time needed to load all the tabs I had.

**Comment by mstange** [comment]
I don't understand your first point - can you link to a profile that's "pretty much empty"? The startup profile you posted in the bug (from your gz.part file) doesn't look empty at all.

The second point is expected - the profiler add-on, like all add-ons, isn't initialized until fairly late in the Firefox startup sequence.

**Comment by mirh** [comment]
> The second point is expected - the profiler add-on, like all add-ons, isn't initialized until fairly late in the Firefox startup sequence.

Well, [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler#Profiling_Firefox_Startup) makes it look like MOZ_PROFILER_STARTUP would solve, or if any at least improve, this aspect. 

If this is the case (gecko profiler initialization has to necessarily be after session restore) though, I guess there's no additional point in this bug report.

**Comment by mstange** [comment]
MOZ_PROFILER_STARTUP makes the Gecko Profiler record profiling data even before the add-on is started. The add-on is just the way to get the data out of the Gecko Profiler. So even if it starts much later, you will still get the data you collected.

That's assuming the buffer was big enough.

**Comment by mirh** [comment]
Oh, ok then. 

> That's assuming the buffer was big enough.

Is MOZ_PROFILER_STARTUP env able to read the value set inside "normal" gecko profiler add-on setting, or can I only specify this via command line?

**Comment by mstange** [comment]
You can specify it via the env variable MOZ_PROFILER_STARTUP_ENTRIES, which defaults to 1000000 (9 bytes per entry, so 9MB).

**Comment by mirh** [comment]
Yes, but ***only exclusively*** via that variable then?
EDIT: just checked, indeed that's it

~~If this is the case, then I guess~~ it should be underlined on the MDN page (and I could close this).

**Comment by mirh** [comment]
Ok, I just noticed MDN is an open wiki. 
I was going to edit it then.. But I noticed @overholt [specifically](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler$compare?to=1236409&from=1231481) wrote the contrary of my observation?

**Comment by mirh** [comment]
Ok, I just noticed MDN is an open wiki. 
I was going to edit it then.. But I noticed @overholt [specifically](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler$compare?to=1236409&from=1231481) wrote the contrary of my observation?

**Comment by overholt** [comment]
@mirh, if @mstange said something to the contrary of what I wrote (or maybe what I refactored), please change it it on MDN :)

**Comment by mirh** [comment]
He actually never replied directly to the question tbh
Though, _I_ tested the thing with  MOZ_PROFILER_STARTUP_ENTRIES, and only there I could finally log the 4-minutes startup.

**Comment by mstange** [comment]
I'll update the documentation. Tweaking settings in the add-on's settings does not change the buffer size for startup profiling.
