### ISSUE TITLE
Shortcut for saving symbolized profile

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/Gecko-Profiler-Addon#5]
Hasal needs an easy way of storing the profile, best even already symbolicated. They are exploring remote debugging protocol, but a shortcut that stores the JSON file to disk might also help in the interim.

**Comment by clarkbw** [comment]
@digitarald Is this still needed?  With the `geckoProfiler` WebExtension API you might be able to do this without anything from this extension.

**Comment by gregtatum** [comment]
Closing as no longer valid.
