### ISSUE TITLE
toolbar icon should use play / paused images

### ISSUE THREAD

**Issue by clarkbw** [firefox-devtools/Gecko-Profiler-Addon#50]
I think we want to keep the color indicator that we have right now but I'd like us to also include smaller play and pause images overlaying the icon (perhaps on the bottom right).  I've heard several people ask about this (you can also hear discussion in this video https://air.mozilla.org/gecko-profiler-introduction/ ) where it needs to be explained.

**Comment by eeejay** [comment]
If I would have the ability, I would label this as an accessibility issue.

**Comment by julienw** [comment]
yeah it would be really good indeed, and not very difficult.

**Comment by suhailsinghbains** [comment]
Hi @clarkbw , can I please work on this bug. I am new to dev-tools

**Comment by julienw** [comment]
Hey @suhailsinghbains, yes sure, please do :) 

I think the easiest is to replace the icon in https://github.com/firefox-devtools/Gecko-Profiler-Addon/blob/master/icons/toolbar_on.png with an icon having a small blue dot at a corner, indicating it's on (like spotify). I find it better than pause/play buttons, where I never know which button is for which state.

**Comment by julienw** [comment]
In #154 we tried what I proposed above, but the result isn't nice enough. We need some more design to be thrown into this issue before moving forward.

**Comment by gregtatum** [comment]
Closing as no longer valid, as we have a new workflow built into Firefox.
