### ISSUE TITLE
Reloading the perf.html tab no longer reconnects to the add-on

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#67]
With the SDK-based add-on, you were able to reload the tab that the add-on opened when you collected a profile, and that  tab was able to retrieve the profile again.

This no longer works.

cc @squarewave

**Comment by squarewave** [comment]
I think the way this needs to be fixed will conflict with #60. Do you want to take a second look at that or can I merge it in @mstange?
