### ISSUE TITLE
Unable to access Profiler settings, on Linux (content overflows dropdown pane)

### ISSUE THREAD

**Issue by dholbert** [firefox-devtools/Gecko-Profiler-Addon#7]
Here's what the profiler dropdown looks like for me (on Linux nightly, profiler version 2.0.11) -- note that the content is clipped, and the settings button is completely missing (because it's too low, I think):

CURRENT BROKEN RENDERING:
![actual-profiler-screenshot](https://cloud.githubusercontent.com/assets/426803/21032390/515ed6a4-bd4d-11e6-82a3-36e856b5ec3f.png)

I believe it's *supposed* to look like this (taking screenshot from the new.cleopatra.io frontpage):

EXPECTED RENDERING:
![expected-profiler-screenshot](https://new.cleopatra.io/26d176436b5f2337f4c88dc2445be71c.png) 

Nightly version: 53.0a1 (2016-12-08) (64-bit)

**Comment by dholbert** [comment]
SNEAKY: After opening the pane, I can scroll the settings button into view if I hit the "Tab" key and then the "Space" key.

But then if I expand the settings area, content is then truncated at the right edge of the pane.  

Screenshot (notice the "1ms", "9MB", and the "Threads" input area):
![Screenshot of expanded + clipped-on-right settings content](https://cloud.githubusercontent.com/assets/426803/21032700/41749e2a-bd4f-11e6-8fb2-521d5cbef60a.png)

**Comment by mstange** [comment]
a6abe810f2c00513dbb145199fa8ea1e6cc39889 makes the settings button accessible. #25 will fix the text being cut of on the right side.

**Comment by mstange** [comment]
This was fixed.
