### ISSUE TITLE
Add mainthreadio feature checkbox

### ISSUE THREAD

**Issue by mikeconley** [firefox-devtools/Gecko-Profiler-Addon#79]
As per this [FAQ](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Gecko_Profiler_FAQ), the Gecko Profiler back-end has the ability to add markers during main thread IO, but there's currently no way of enabling that feature from the add-on.

We should add that ability.

**Comment by mstange** [comment]
The WebExtension API needs to be updated to allow this feature, see [bug 1365400](https://bugzilla.mozilla.org/show_bug.cgi?id=1365400).

**Comment by mstange** [comment]
That bug has been fixed, so we can add this now.

**Comment by gregtatum** [comment]
This won't be added, since it's already in the new profiler workflow built into Firefox.
