### ISSUE TITLE
Support unattended mode for upload & share profile data

### ISSUE THREAD

**Issue by kanru** [firefox-devtools/Gecko-Profiler-Addon#80]
In order to capture and share profile in automation tools like Hasal we need a way to automatically symbolicate and upload profile data then record the url somewhere that can retrieved test runners.

Currently perf-html.io requires user to click a button and copy the url which is not very machine friendly.

**Comment by legnaleurc** [comment]
I think we will need to expose this function:
https://github.com/devtools-html/perf.html/blob/15efd1b0eb42eda9d5ad0f41e807cfbf3a0b430a/src/content/containers/ProfileSharing.js#L107

**Comment by gregtatum** [comment]
I'm not sure of the context here, but this add-on is now deprecated. Feel free to re-file any issues here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Performance+Tools+%28Profiler%2FTimeline%29 or chat with the profiler team on https://chat.mozilla.org/#/room/#profiler:mozilla.org
