### ISSUE TITLE
With latest addon and nightly, perf.html doesn't detect the addon when using the debugging server

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#81]
STR:
1. Change the addon's server preference to `http://localhost:4242/`
2. Go to http://localhost:4242/ (with the server launched)

Expected:
* Addon is detected and I get information about how to record profiles.

Actual:
* Addon isn't detected and I don't get the information about how to install the addon.

**Comment by mstange** [comment]
That's a known issue and somewhat intentional, see https://github.com/devtools-html/Gecko-Profiler-Addon/blob/7fd6285b0c71691cb176cb1626bedc70ac263975/content-home.js#L3

**Comment by julienw** [comment]
If this is intentional I'm gonna close the bug.
