### ISSUE TITLE
Publish some kind of privacy policy

### ISSUE THREAD

**Issue by mikeconley** [firefox-devtools/Gecko-Profiler-Addon#82]
[At least one user](https://www.reddit.com/r/firefox/comments/6cs292/why_is_firefox_much_slower_than_chrome/dhxbqxh/) has expressed an interest in reading a privacy policy for the Gecko Profiler Add-on.

I wonder if we should make it more clear to end-users:

1. What happens when the add-on is running (and how no profile data is sent yet)
2. What happens when the "Share" button is clicked (although I suppose the built-in privacy warning covers some of that)
3. What happens to the data that is sent, where it's stored, its lifetime, etc.

**Comment by gregtatum** [comment]
The front-end has a privacy policy, and the rest of the infrastructure is in Firefox. Marking as resolved.
