### ISSUE TITLE
Drastically increase displayed overhead when going below 1ms on Windows

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#83]
On Windows we now use a busy-loop to implement sub-1ms waits. This loop eats one core per profiled process and has very high overhead. We should reflect that overhead in the UI.

**Comment by gregtatum** [comment]
Closing since the addon is deprecated. The new overhead mechanism isn't built at the time of this writing. Track it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1597383
