### ISSUE TITLE
starting Firefox prints: WARN	Please specify whether you want browser_style or not in your browser_action options.

### ISSUE THREAD

**Issue by dbaron** [firefox-devtools/Gecko-Profiler-Addon#85]
When I start up Firefox in a profile with the Gecko Profiler addon installed, I see the following printed to the console:

> 1497593825592	addons.webextension.geckoprofiler@mozilla.com	WARN	Please specify whether you want browser_style or not in your browser_action options.

Seems like this is saying something should be fixed.

**Comment by mstange** [comment]
The PR #84 includes a fix for this.

**Comment by mstange** [comment]
Fixed by #86.
