### ISSUE TITLE
Add a dark theme icon

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/Gecko-Profiler-Addon#88]
Here's what the extension looks like on Firefox dark theme : 

<img width="220" alt="screen shot 2017-06-28 at 10 16 33" src="https://user-images.githubusercontent.com/578107/27650789-e6ceab74-5bea-11e7-8677-c7cfdab3e126.png">

It is not ideal, and it would be really nice having a dedicated icon for the dark mode.
This should be doable with the patch from [Bug 1329242](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242) , even if we should wait it to be on release since the way it handles icons would not work with Firefox version without the patch.

**Comment by julienw** [comment]
v56 is stable now, maybe we can try to implement this now :)

**Comment by julienw** [comment]
(see also https://bugzilla.mozilla.org/show_bug.cgi?id=1377302, I don't know which solution is best)

**Comment by julienw** [comment]
I did https://github.com/devtools-html/Gecko-Profiler-Addon/compare/master...julienw:add-dark-icon but it doesn't work for me :( Maybe I missed something...

**Comment by julienw** [comment]
Oh, I know, this is because of https://github.com/devtools-html/Gecko-Profiler-Addon/blob/master/background.js#L173

I guess we'll need to detect it but I don't think this is possible at the moment... Which leaves us with https://bugzilla.mozilla.org/show_bug.cgi?id=1377302 which isn't enabled yet.

**Comment by julienw** [comment]
According to the [documentation for browserAction](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/setIcon) we could use "undefined" to revert to the main icon. So I tried it and it still doesn't work. Actually it doesn't work even when I completely remove this line :/

**Comment by julienw** [comment]
Yay, made it work :D

**Comment by nchevobbe** [comment]
\o/ Pretty icon incoming
