### ISSUE TITLE
Setting the profiler URL fails intermittently

### ISSUE THREAD

**Issue by gregtatum** [firefox-devtools/Gecko-Profiler-Addon#89]
STR:
 * Go to about:addons on nightly with the add-on installed
 * Set the url to something different
 * It either fails the first time, or fails intermittently.

The browser console fails with: [`win.PopupNotifications is undefined`](http://searchfox.org/mozilla-central/rev/3a3af33f513071ea829debdfbc628caebcdf6996/browser/modules/ExtensionsUI.jsm#441)

I'll also file a bug on Bugzilla.

**Comment by gregtatum** [comment]
Filed a bug against the WebExtensions: https://bugzilla.mozilla.org/show_bug.cgi?id=1383038

**Comment by PaulBone** [comment]
Is this the error message you see? This fails every time for me.

![gecko-profiler-url](https://user-images.githubusercontent.com/3138117/30261081-41d2d014-970e-11e7-9360-64db294208fe.png)

**Comment by PaulBone** [comment]
This has me blocked, I cannot test my changes to the profiler's conversion code.

**Comment by mstange** [comment]
Yes, that's that error. The Firefox bug still hasn't been fixed :-(

Workaround is:
 - Attempt to change the URL, get the error.
 - Open the Browser Console.
 - Find the error message in the console for this error.
    > Error: An unexpected error occurred  options.js:36:11
 - Click the link to options.js on the right end of that line.
 - A tab with the URL `view-source:moz-extension://<some add-on ID>/options.js` will open
 - Change the filename from `options.js` to `options.html` and remove the `view-source:` part at the beginning.
 - You should now see the `Profile viewer URL:` UI again.
 - Try changing the profile viewer URL again, from here. It should work now.

**Comment by PaulBone** [comment]
Thanks, that workarround has worked,

**Comment by gregtatum** [comment]
Closing as no longer valid with the new UI.
