### ISSUE TITLE
Consider disabling the profiler after capturing the data

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#91]
After capturing the data the profiler is still on, which is not useful because we're now profiling the profiler front-end.

**Comment by gregtatum** [comment]
See #45 for a proposal of changing the workflow.

**Comment by julienw** [comment]
cc @ochameau

**Comment by ochameau** [comment]
I imagine I want #45 option 3 "Stop profiling on analyze".
When you set agressive settings like 0.1ms... it takes a while to open results, it is very frustrating.
I imagine it would be much faster if profilers wasn't profiling itself ;)

**Comment by gregtatum** [comment]
This is resolved in the new UI.
