### ISSUE TITLE
Add a mechanism to name Workers

### ISSUE THREAD

**Issue by juj** [firefox-devtools/Gecko-Profiler-Addon#93]
Working on profiling a large 3D engine, with several dedicated threads for audio, physics, statistics, particles, rendering, networking, file io, decompression, game logic and a generic task pool, it takes a lot of time to be able to identify which one is which. In Emscripten, Workers are always loaded from the same laucher url "pthread-main.js" (or from a blob url "blob://long-unreadable-uuid"), see below

<img width="882" alt="screenshot from 2017-08-24 10-01-09" src="https://user-images.githubusercontent.com/225351/29654184-e304bf0a-88b4-11e7-9a5b-309a168e7260.png">

In that image, see on the left, where each thread is name `"DOM Worker 'pthread-..."`, which is difficult to identify the interesting thread.

It would be very useful if there was a way for JS code to assist the profiler by being able to call something like  `workerglobalscope.geckoProfiler.setCallingThreadName('audioThread');`. I would then be able to hook these types of calls into the program I am profiling.

**Comment by juj** [comment]
Ops, sorry, should I have reported this and #92 to https://github.com/devtools-html/perf.html/issues instead? What is the difference between these two? My understanding is that perf.html == gecko profiler add-on, but that probably is not accurate?

**Comment by gregtatum** [comment]
No worries, the division of parts is a little confusing. I don't mind moving issues to the proper place, or re-file things.

* Gecko Profiler on m-c/Bugzilla. is the internal implementation in Gecko. So anything C++ and profiler specific goes there.
* Gecko Profiler Addon is a small codebase that is mainly a recording panel. It activates the Gecko Profiler, and marshals the data to perf.html.
* perf.html is the client visualizing the data. It's the more high-level component, and is probably the best place to file discussion issues, issues with the client, and things that require orchestrating changes across repos.

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625540
