### ISSUE TITLE
Error message for trying to set the URL is difficult to read with "dark" colours.

### ISSUE THREAD

**Issue by PaulBone** [firefox-devtools/Gecko-Profiler-Addon#94]
With "dark" colours (firefox preferences -> colours, forground = white, background = black, don't use system colours and always override page colours) the error message for changing the URL is really difficult to read.  For an hour or more I didn't even know there was an error message here until I pulled up the devtools inspector.
![gecko-profiler-url](https://user-images.githubusercontent.com/3138117/30261184-a99faf82-970e-11e7-9c3f-890d723ba356.png)

**Comment by gregtatum** [comment]
Closed as no longer needed, as the URL is now set by the pref `devtools.performance.recording.ui-base-url`
