### ISSUE TITLE
Profiler should track style threads by default

### ISSUE THREAD

**Issue by upsuper** [firefox-devtools/Gecko-Profiler-Addon#95]
It seems that Gecko Profiler currently doesn't track style threads by default, this could be a problem that we would not know what the style thread is doing from profiles.

**Comment by gregtatum** [comment]
Defaults are now decided by presets. If this is still need, please consider filing a bug to change a preset in https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Performance+Tools+%28Profiler%2FTimeline%29
