### ISSUE TITLE
Documentation for possible targets for "Threads:" profiling option

### ISSUE THREAD

**Issue by gregtatum** [firefox-devtools/Gecko-Profiler-Addon#97]
This was posted by @juj in [perf.html#608](https://github.com/devtools-html/perf.html/issues/608)
---
In 
![threads](https://user-images.githubusercontent.com/225351/31134776-c33769f8-a86b-11e7-9577-3176d34edbb8.png)

it is possible to choose which threads to profile. Discussing via email, I heard that there is a "Worker" option that can be added there, which is great and works well.

1) What other options are there available in addition to `GeckoMain`, `Compositor` and `Worker`?

2) Tried to look at https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler to find answer to above, and info about `Worker`, but was not able to find documentation about these options. Does there exist a doc page about these settings?

Background is that I am trying to profile https://bugzilla.mozilla.org/show_bug.cgi?id=1402958, which is reported to run slow in compiling wasm code, but I am unable to see this in a Cleopatra view. The best I am able to get is

https://perfht.ml/2xPDwus

which looks as if all threads are waiting for an event, and no thread is working, but that is not the case, and there is still an unprofiled thread that is doing some work.

**Comment by gregtatum** [comment]
mstange replied:
---
Using Instruments and running that testcase, I could see that the CPU usage was inside a JS HelperThread. Unfortunately, this thread is currently not registered with the Gecko profiler. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1405374 about this.

At the moment, the trick to see what threads are available is to set the thread filter to just a comma (","), which will cause it to profile all registered threads. Then the resulting profile can be used to get a list of the thread names which are available. This definitely needs a better UI, https://bugzilla.mozilla.org/show_bug.cgi?id=1321607 .

**Comment by gregtatum** [comment]
juj replied:
---
Thanks, very helpful!

I really like there type of UX where there are small superscript <sup>?</sup> marks added after items, which would then give info tidbits when hovered over. Those are generally on the moderately easier side to implement, they don't clutter up UI with verbose info text by default, and they avoid the issue that people won't find the features unless they know to navigate to a specific doc page in question. Perhaps the info could be presented via a "Threads:<sup>?</sup>" style of presentation.

That is, if going forward the UI will still have a text edit box, where the list of threads is expected to be written.

**Comment by julienw** [comment]
From a discussion with @nbp yesterday, I think we need also a button to reset to the default: after removing everything it's difficult to find what the defualt was.

**Comment by past** [comment]
After [bug 1444765](https://bugzilla.mozilla.org/show_bug.cgi?id=1444765) it is now possible to filter by process ID in order to limit sampling to the threads that belong in the specified process. The format is `pid:<n>`.

**Comment by past** [comment]
Isn't this fixed after #125?

**Comment by gregtatum** [comment]
Looks like it
