### ISSUE TITLE
Make it possible to "capture and save" a profile instead of opening perf-html.io

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/Gecko-Profiler-Addon#98]
This comes from @fqueze.

This is for when he profiles on a old computer: capturing into perf-html, symbolicating, and sharing takes at least 30 minutes on this machine.

From the addon we could have a button to capture and save the profile as a json file, so that it can be loaded on a better computer -- and symbolicated there too once we have https://github.com/devtools-html/perf.html/issues/253.

**Comment by grahamperrin** [comment]
💯 👍 

For Mozilla bug [1441041 - memory not freed after ceasing to visit some types of content](https://bugzilla.mozilla.org/show_bug.cgi?id=1441041), my first ever attempt to use the extension, with Nightly: 

- I gave up after waiting a few hours. 

My second attempt, with release 59.0.1, I have been waiting more than an hour with perf.html:

> Waiting for symbol tables for libraries CoreFoundation, libsystem_kernel.dylib, AppKit, Foundation, Lib…

**Comment by gregtatum** [comment]
Moved to https://github.com/firefox-devtools/Gecko-Profiler-Addon/issues/98
